language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

// build.gradle
apply plugin: "java"
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}
dependencies {
    testCompile 'junit:junit:4.11'
}